image: ubuntu/lts

repositories:
  - https://packages.erlang-solutions.com/erlang/debian/pool/esl-erlang_21.3.8.17-1~ubuntu~bionic_amd64.deb
packages:
  - erlang

sources:
  - https://git.sr.ht/~k32/Lee

tasks:
  - prepare: |
      wget https://github.com/erlang/rebar3/releases/download/3.14.0/rebar3
      chmod +x rebar3
      sudo mv rebar3 /usr/local/bin/rebar3

  - make: |
      make
